[2024-10-24T14:31:29.807+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_second_dag.inaccurate scheduled__2024-10-23T00:00:00+00:00 [queued]>
[2024-10-24T14:31:29.816+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_second_dag.inaccurate scheduled__2024-10-23T00:00:00+00:00 [queued]>
[2024-10-24T14:31:29.816+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-10-24T14:31:29.830+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): inaccurate> on 2024-10-23 00:00:00+00:00
[2024-10-24T14:31:29.834+0000] {standard_task_runner.py:57} INFO - Started process 238 to run task
[2024-10-24T14:31:29.838+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_second_dag', 'inaccurate', 'scheduled__2024-10-23T00:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/my_second_dag.py', '--cfg-path', '/tmp/tmprozktduv']
[2024-10-24T14:31:29.840+0000] {standard_task_runner.py:85} INFO - Job 43: Subtask inaccurate
[2024-10-24T14:31:29.893+0000] {task_command.py:410} INFO - Running <TaskInstance: my_second_dag.inaccurate scheduled__2024-10-23T00:00:00+00:00 [running]> on host 53db25f57fca
[2024-10-24T14:31:29.994+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_second_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2024-10-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-23T00:00:00+00:00'
[2024-10-24T14:31:29.996+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-24T14:31:29.997+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "echo 'inaccurate'"]
[2024-10-24T14:31:30.007+0000] {subprocess.py:86} INFO - Output:
[2024-10-24T14:31:30.018+0000] {subprocess.py:93} INFO - inaccurate
[2024-10-24T14:31:30.019+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-24T14:31:30.053+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=my_second_dag, task_id=inaccurate, execution_date=20241023T000000, start_date=20241024T143129, end_date=20241024T143130
[2024-10-24T14:31:30.095+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-10-24T14:31:30.112+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
